backend:
  name: github
  repo: wenhaoqiasd/gatsby-netlifycms
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"

media_folder: static/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: src/markdown/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: class, label: Class, widget: select, options: ["draft", "stories"]}
      - { name: slug, label: Slug }
      - { name: title, label: Title }
      - { name: cover, label: Cover, widget: image }
      - { name: date, label: Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }
      - { name: tags, label: Tags, widget: list }
      - { name: color, label: Color, widget: color, enableAlpha: true }
      
  - name: page
    label: Page
    folder: src/markdown/page
    create: true
    fields:
      - { name: path, label: Path }
      - { name: class, label: Class, widget: select, options: ["draft", "others"]}
      - { name: slug, label: Slug }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }
